steps:
- name: 'gcr.io/cloud-builders/docker'
  # args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-docker-repo/test:tag1','--build-arg=ENV=$_PID', '.' ]
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-docker-repo/test:tag1', '.' ]
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  
images:
- 'gcr.io/$PROJECT_ID/quickstart-docker-repo/test:tag1'
# [END cloudbuild_quickstart_build]
# substitutions:
#   _PID: $PROJECT_ID
options:
  logging: CLOUD_LOGGING_ONLY
